apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: levelup-s3-crud-CHANGE-ME
  labels:
    role: levelup-s3-iam-role-CHANGE-ME
    crossplane-demo: levelup-managed-resources
spec:
  forProvider:
    policy: |-
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [ 
              "s3:ListAllMyBuckets",
              "s3:GetBucketLocation"
            ],
            "Resource": "*"
          },
          {
            "Effect":"Allow",
            "Action":["s3:ListBucket"],
            "Resource":"arn:aws:s3:::levelup-CHANGE-ME"
          },
          {
            "Effect": "Allow",
            "Action": [
              "s3:PutObject",
              "s3:GetObject",
              "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::levelup-CHANGE-ME/*"
          }
        ]
      }