apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketOwnershipControls
metadata:
  name: levelup-ownership-torg
  labels:
    crossplane-demo: levelup-managed-resources
spec:
  forProvider:
    bucket: levelup-torg
    region: us-west-2
    rule:
      - objectOwnership: BucketOwnerPreferred
